stages:
  #- init
  - validate
  - plan
  - apply
  - destroy
  
image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
    
before_script:
  - export AWS_ACCESS_KEY="${AWS_ACCESS_KEY_ID}"
  - export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}"
  - export AWS_S3_LOCTION="${AWS_S3_LOCTION}"
  - export AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION}"
  - export DEPLOY_ENVIRONMENT_FILE="${DEPLOY_ENVIRONMENT}".tfvars
  - export TERRAFORM_WORK_SPACE=$(echo "$DEPLOY_ENVIRONMENT" | sed 's/_env//g')
  - rm -rf .terraform
  - terraform --version
  - terraform init

validate:
  stage: validate
  script:
    - terraform validate 
  when: manual

plan:
  stage: plan
  script:
    - terraform workspace select "$TERRAFORM_WORK_SPACE"
    - terraform plan -lock=false -var-file="$DEPLOY_ENVIRONMENT_FILE" -out "planfile"
  when: manual 
  dependencies:
    - validate
  artifacts:
    paths:
      - planfile

apply:
  stage: apply
  script:
    - terraform workspace select "$TERRAFORM_WORK_SPACE"
    - terraform apply -lock=false --auto-approve -var-file=$DEPLOY_ENVIRONMENT_FILE
  dependencies:
    - plan
  when: manual

destroy:
  stage: destroy

  script:
    - terraform workspace select "$TERRAFORM_WORK_SPACE"
    - terraform destroy -lock=false --auto-approve -var-file=$DEPLOY_ENVIRONMENT_FILE
  dependencies:
    - apply
  when: manual
