variable "region" {}
variable "project_name" {}
variable "vpc_cidr" {}
variable "public_subnet_az1_cidr" {}
variable "public_subnet_az2_cidr" {}
variable "frontend_website_bucket" {}
variable "frontend_index_document" {}
variable "frontend_ssl_certificate_arn" {}
variable "frontend_domain_name" {}
variable "frontend_cname_record_ttl" {}
variable "frontend_cname_record_value" {}
variable "frontend_route53_zone_id" {}
variable "frontend_cname_record_name" {}
variable "ecr_registry_name" {}
variable "ecs_log_group_name" {}
variable "ecs_role_name" {}
variable "ecs_security_group_name" {}
variable "ecs_task_family" {}
variable "ecs_service_name" {}
variable "ecs_task_desired_count" {}
variable "ecs_autoscaling_ec2_max_size" {}
variable "ecs_autoscaling_ec2_min_size" {}
variable "ecs_autoscaling_ec2_desired_capacity" {}
variable "ec2_role_name" {}
variable "ec2_policy_name" {}
variable "ecs_node_role_name" {}
variable "ecs_node_instance_profile_name" {}
variable "ecs_node_sg_name_prefix" {}
variable "ecs_ec2_launch_template_name_prefix" {}
variable "ecs_ec2_instance_type" {}
variable "ecs_autoscaling_group_name" {}
variable "ecs_autoscaling_group_min_size" {}
variable "ecs_autoscaling_group_max_size" {}
variable "ecs_autoscaling_group_health_check_grace_period" {}
variable "ecs_autoscaling_group_health_check_type" {}
variable "ecs_autoscaling_group_protect_from_scale_in" {}
variable "ecs_autoscaling_group_tag_name" {}
variable "ecs_autoscaling_group_tag_value" {}
variable "ecs_capacity_provider_name" {}
variable "ecs_capacity_provider_managed_termination_protection" {}
variable "ecs_capacity_provider_managed_scaling_maximum_scaling_step_size" {}
variable "ecs_capacity_provider_managed_scaling_minimum_scaling_step_size" {}
variable "ecs_capacity_provider_managed_scaling_status" {}
variable "ecs_capacity_provider_managed_scaling_target_capacity" {}
variable "ecs_cluster_capacity_provider_base" {}
variable "ecs_cluster_capacity_provider_weight" {}
variable "ecs_cluster_name" {}
variable "ecs_container_name" {}
variable "backend_container_port" {}
variable "backend_ecr_image_location" {}
variable "backend_host_port" {}
